INSERT INTO trait_pairs (trait_1, trait_2, description) VALUES
                                                            ('Extraverti', 'Introverti', 'Préférence pour la socialisation ou la solitude'),
                                                            ('Aventureux', 'Prudent', 'Prise de risques vs recherche de sécurité'),
                                                            ('Indépendant', 'Axé sur le couple', 'Préférence pour l’autonomie ou la vie de couple'),
                                                            ('Spontané', 'Organisé', 'Actions impulsives vs planification organisée'),
                                                            ('Idéaliste', 'Réaliste', 'Vision idéaliste vs vision ' ||
                                                                                      'ancrée dans la réalité'),
                                                            ('Ambitieux', 'Décontracté', 'Forte motivation professionnelle vs style de vie tranquille'),
                                                            ('Créatif', 'Logique', 'Expression artistique vs pensée rationnelle'),
                                                            ('Sociable', 'Réservé', 'Ouverture aux autres vs discrétion'),
                                                            ('Noctambule', 'Matinal', 'Préférence pour la nuit vs le matin'),
                                                            ('Passionné', 'Calme', 'Intensité émotionnelle vs tempérament tranquille'),
                                                            ('Drôle', 'Sérieux', 'Préférence pour l’humour vs sérieux'),
                                                            ('Romantique', 'Pragmatique', 'Préférence pour le romantisme vs approche réaliste des relations'),
                                                            ('Axé carrière', 'Axé famille', 'Orientation vers la carrière vs priorité pour la vie familiale'),
                                                            ('Sportif', 'Casual', 'Engagement pour la pratique sportive vs mode de vie détendu'),
                                                            ('Généreux', 'Économe', 'Tendance à donner ou partager vs économie de ressources'),
                                                            ('Audacieux', 'Prévisible', 'Prise d’initiatives audacieuses vs stabilité et prévisibilité'),
                                                            ('Organisé', 'Impulsif', 'Préférence pour l’organisation vs actions spontanées'),
                                                            ('Intuitif', 'Analytique', 'Décision basée sur les ressentis vs logique et analyse'),
                                                            ('Rêveur', 'Pieds sur terre', 'Tendance à imaginer et rêver vs pragmatisme'),
                                                            ('Posé', 'Dynamique', 'Calme et réflexion vs énergie et action'),
                                                            ('Curieux', 'Satisfait', 'Tendance à explorer de nouvelles choses vs contentement'),
                                                            ('Engagé', 'Libre', 'Investissement dans des projets ou relations vs désir de liberté'),
                                                            ('Spirituel', 'Cartésien', 'Approche spirituelle vs rationalité scientifique'),
                                                            ('Amateur d’art', 'Cartésien', 'Intérêt pour les arts et la culture vs logique rationnelle'),
                                                            ('Épicurien', 'Sobre', 'Préférence pour le plaisir des sens vs mode de vie modéré'),
                                                            ('Nerd', 'Populaire', 'Passion pour des intérêts spécifiques vs popularité sociale'),
                                                            ('Leader', 'Suiveur', 'Tendance à diriger vs suivre les autres'),
                                                            ('Intello', 'Manuel', 'Préférence pour l’intellect et les activités mentales vs le travail manuel'),
                                                            ('Baroudeur', 'Casanier', 'Amour des voyages et de l’aventure vs préférence pour le confort de la maison');
